CREATE TABLE IF NOT EXISTS chat_gift_transactions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    thread_id INT UNSIGNED NOT NULL,
    sender_user_id INT UNSIGNED NULL,
    sender_name VARCHAR(190) NOT NULL,
    sender_avatar_asset VARCHAR(255) NULL,
    recipient_user_id INT UNSIGNED NULL,
    recipient_name_snapshot VARCHAR(190) NULL,
    gift_id INT UNSIGNED NOT NULL,
    gift_name_snapshot VARCHAR(190) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price_coins INT NOT NULL DEFAULT 10,
    total_price_coins INT NOT NULL DEFAULT 10,
    platform_fee_coins INT NOT NULL DEFAULT 0,
    creator_earning_diamonds INT NOT NULL DEFAULT 0,
    platform_commission_percent DECIMAL(5,2) NOT NULL DEFAULT 50.00,
    created_at DATETIME NOT NULL,
    INDEX idx_chat_gifts_thread (thread_id),
    INDEX idx_chat_gifts_sender (sender_user_id),
    INDEX idx_chat_gifts_recipient (recipient_user_id),
    CONSTRAINT fk_chat_gifts_thread FOREIGN KEY (thread_id) REFERENCES chat_threads(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_gifts_sender FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_chat_gifts_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_chat_gifts_gift FOREIGN KEY (gift_id) REFERENCES gifts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
